version: "3.1"
services:

  webserver:
    image: nginx:alpine
    restart: always
    depends_on:
      - php
    links:
      - php
    networks:
      - frontend      
    ports:
      - 8000:80
    volumes:
      - ./opensid:/public_html:rw
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx

  php:
    networks:
      - backend
      - frontend
    build:
      context: ./
      dockerfile: .docker/Dockerfile.php
    ports:
      - 9000:9000
    depends_on:
      - db
    volumes:
      - ./opensid:/public_html:rw
      - ./.docker/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf

  db:
    restart: always
    build:
      context: ./
      dockerfile: .docker/Dockerfile.db
    ports:
      - 3307:3306
    networks:
      - backend
    environment:
      # MYSQL_ROOT_PASSWORD: rahasia
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: opensid
      MYSQL_USER: opensid
      MYSQL_PASSWORD: rahasia
    volumes:
      - ./db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  frontend:
  backend:
