version: "3.1"
services:

  webserver:
    image: nginx:alpine
    restart: always
    depends_on:
      - php
    networks:
      - frontend
    ports:
      - 80:80
    volumes:
      - ./:/public_html:rw
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf

  php:
    networks:
      - backend
      - frontend
    build:
      context: ./
      dockerfile: .docker/Dockerfile.php
    ports:
      - 9000:9000
    depends_on:
      - db
    volumes:
      - ./:/public_html:rw
      - ./.docker/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf

  db:
    restart: always
    build:
      context: ./
      dockerfile: .docker/Dockerfile.db
    networks:
      - backend
    environment:
      # MYSQL_ROOT_PASSWORD: rahasia
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: opensid
      MYSQL_USER: opensid
      MYSQL_PASSWORD: rahasia
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - frontend
      - backend
    environment:
      PMA_HOST: db
      PMA_PORTS: 3306
      UPLOAD_LIMIT: 100M
      HIDE_PHP_VERSION: 1
    ports:
      - 8081:80
    volumes:
      - /sessions

volumes:
  db_data:

networks:
  frontend:
  backend:
